import React, { Component } from 'react';
import './App.css';
import 'semantic-ui-css/semantic.min.css';
import {Form, Segment, Button, Header, Input } from 'semantic-ui-react';

class App extends Component {
  state = {
    value: '',
    message: 'Your Safe URL :'
  }


  onSubmit = async (event) => {
    event.preventDefault();

    const IPFS = require('ipfs-mini');
    const ipfs = new IPFS({ host: 'ipfs.infura.io', port: 5001, protocol: 'https' });
    const data = "Here's the link to the real video : "+this.state.value;
    ipfs.add(data, (err,hash) => {
      if(err){
        this.setState({ message: err });
      }
      this.setState({ message: 'https://ipfs.infura.io/ipfs/'+hash });

    })
  };

  render() {
    return (
      <div className="container-fluid mt-7" align="center">
      <div className="row">
      <main role="main" className="col-lg-12 ml-auto mr-auto" style={{ maxWidth: '980px' }}>
      <div className="content mr-auto ml-auto">
      <Header as='h2' textAlign='center' block>
        Deepfake Protector
        </Header>
        <Header as='h3' textAlign='center' block>
        A deepfake is a fake photo, video or story generated by AI neural networks. Deepfake creators use artificial intelligence and machine learning algorithms to imitate the work and characteristics of real humans.
        <br />
        <br />
        Here on deepfake protector you can paste the url of your video. You will get an ipfs url which contains the link to the real video.
        <br />
        <br />
        You can then share that ipfs url with anyone you want.
         </Header>

        <Form onSubmit={this.onSubmit}>
        <Form.Field>
        <table>
        <tr align="center"><button class="ui youtube button">
          <i aria-hidden="true" class="youtube icon"></i>
          Enter YouTube Link
        </button><br /><br /></tr>
        <tr>
        <th width="700px">
          <Input
          fluid
          placeholder="Enter or paste the url.."
          size="large"
          label="Link"
          labelPosition="left"
          value={this.state.value}
          onChange={event => this.setState({ value: event.target.value })}
           />
           </th>
           <th>
           <Button primary size="large">Enter</Button>
           </th>
           </tr>
           </table>
        </Form.Field>
        </Form>
        <Segment><h2>{this.state.message}</h2></Segment>

      </div>
      </main>
      </div>
      </div>
    );
  }
}

export default App;
